export XDG_CONFIG_HOME=~/.config
export XDG_DATA_HOME=~/.data

export ZSH_CUSTOM=/usr/share/oh-my-zsh/custom

export EDITOR=nvim
export VISUAL=nvim

export LESSKEY=~/.config/less/less_config

export RANGER_LOAD_DEFAULT_RC=FALSE

export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export CARGO_HOME="$XDG_DATA_HOME"/cargo

export GTK2_RC_FILES=/usr/share/themes/Arc-Dark/gtk-2.0/gtkrc
export GTK_THEME=Arc-Dark
